project:
  type: website
  output-dir: docs
  resources:
    - CNAME


website:
  title: "Ebenezer Makinde"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: writing.qmd
        text: Writing


format:
  html:
    theme: flatly
    toc: false
    css: styles.css
